const ROUTE_NAME = {
  main: "/",
  notfound:"/not-found",
  sales: "/sales-performance",
  target: "/target-performance",
  actual: "/actual-performance",
  product: "/product-box",
  checking: "/app-checking",
  chatbox: "/chat-box",
  commission: "/commission",
  project: "/project-management",
  report: "/report",
  upload: "/upload-center",
  proportion: "/proportion-of-products",
  reject: "/reject-reason-rate",
  statistics: "/statistics",
  pos_admin:"/pos-admin",
  store: "/pos-admin/store",
  partner: "/pos-admin/partner",
  admin_tools:"/admin-tools",
  userManage: "/admin-tools/user-management",
  role: "/admin-tools/role",
  position: "/admin-tools/position",
  menu: "/admin-tools/menu",
  widget: "/admin-tools/widget",
  executive: "/admin-tools/executive",
  productbox: "/admin-tools/product-box",
  policies: "/admin-tools/incentive-policies",
  scheme_group: "/admin-tools/scheme-groups",
  scheme_rate: "/admin-tools/scheme-rate",
  adj_policies: "/admin-tools/adjustment-policies",
  campaign_rate: "/admin-tools/campaign-rate",
  region_rate: "/admin-tools/region-rate",
  province_rate: "/admin-tools/province-rate",
  paid_settings: "/admin-tools/paid-settings",
  payment_settings: "/admin-tools/payment-settings",
  upload_center:"/admin-tools/upload-center",
  cron_job:"/admin-tools/cron-job",
};

export default ROUTE_NAME;
